### ISSUE TITLE
Add defaults for mariadb cluster config

### ISSUE THREAD

**Issue by ampersand8** [swisscom/open-service-broker#177]
# Problem
If fields like `vendor` or `driver` in the mariadb cluster config is forgotten, the service does not work. This is unfortunate, as most of the times those will be configured with the default values `mysql` and `com.mysql.cj.jdbc.Driver`.

https://github.com/swisscom/open-service-broker/blob/v5.0.13/broker/src/main/resources/application.yml#L91-L92

# Requirements
- [x] Use defaults if not configured for the fields `vendor` and `driver` in mariadb cluster config

# Proposal
- Set defaults for the fields `vendor` and `driver`

**Comment by meip** [comment]
Good catch, thx!

**Comment by ampersand8** [comment]
Fixed with #178
