### ISSUE TITLE
CredHub Set Credentials does no longer support `overwrite`

### ISSUE THREAD

**Issue by Lafunamor** [swisscom/open-service-broker#181]
# Problem
Starting with version 2.0.0 of CredHub the `overwrite` flag for set credential requests are no longer supported.

# Requirements
- Adapt OSB to the [breaking changes in CredHubs v2.0.0 release](https://github.com/pivotal-cf/credhub-release/releases/tag/2.0.0)

# Links
- [CredHubs v2.0.0 release](https://github.com/pivotal-cf/credhub-release/releases/tag/2.0.0)

**Comment by seilc1** [comment]
fixed
