### ISSUE TITLE
Refactor field internalName in CFService

### ISSUE THREAD

**Issue by meip** [swisscom/open-service-broker#19]
The field `internalName` in `CFService` and `Plan` is used to reference a corresponding `ServiceProvider`. This name is somehow misleading when a ServiceDefinition got pushed (as seen in #9).
I suggest to rename these fields to `serviceProviderName`. This migration isn't trivial since backwards compatibility should be given. I suggest the following migration path:

1. Introduce a new field with the appropriate name
1. Add a mapping functionality to map the old field name to the new one
1. Remove this mapping functionality with the next major release

**Comment by mcelep** [comment]
@meip, should we use a field called **serviceProviderClass** (instead of serviceProviderName) ?

**Comment by Zee-Khan** [comment]
@mcelep As it stands right now, we concatenate "ServiceProvider" to internalName. If we use serviceProviderClassName, we can remove the subfix and anticipate the entire value of serviceProviderClassName to be the expected bean. What do you think?

**Comment by mcelep** [comment]
@Zee-Khan using the full class name(be it fully qualified or simple ) is fine, what I meant was using 'serviceProviderClass' as the database column instead of 'serviceProviderClassName'.
