### ISSUE TITLE
Nested Catalog

### ISSUE THREAD

**Issue by meip** [swisscom/open-service-broker#45]
Today OSB supports a fixed set of services (Catalog). These services strictly follow the rule that after provision only binds can follow. This limits how and what the customer can consume from a service.

Instead for certain services i.e. dedicated MySQL Cluster something between provision and bind is required to also provision schemas on the cluster and later bind these schemas to the app instead of binding the whole cluster. This requirement may can be resolved with a Nested Catalog.

**Topics to discuss**
* Design a Service Provider which can provision catalog items
* Catalog management
* Platform support for nested/dynamic catalog items
  * i.e. for Cloud Foundry `cf update-service-broker` and `cf enable-service-access`

**Comment by mcelep** [comment]
@meip I'm not sure if I get it right... do you mean to extend the service catalog with some custom actions?
Please elaborate and provide some examples if possible.

**Comment by MatthiasWinzeler** [comment]
@mcelep Imagine the following:
As a platform user (i.e. CF space developer), I want to create a dedicated MariaDB cluster. 
I would achieve this by provisioning a service `dedicated-mariadb` from the catalog. The service provider would create the necessary VMs. 
Binding directly to this service instance (= cluster) does not make sense (so service `dedicated-mariadb` is not bindable) - I would like to provision databases on the just created cluster. 

To achieve this, service provisioning of `dedicated-mariadb` would create a new catalog item `dedicated-mariadb-<guid>`. I can then create service instances (= databases) and bindings (=users) on this service.

This is what we call a dynamic/nested catalog.

**Comment by mcelep** [comment]
@MatthiasWinzeler it might a bad idea to fiddle with the catalog. CF cashes the catalog info and every time service definitions are updated CC needs to poll the SB again. Moreover, one would also potentially need to make sure that the newly created service is only visible from the right org. Ideally SB should not need call a platform (back). Also billing could be affected.

Some different options:
1) Disable binding: For certain services the simple binding SB offers does not cut it, so SB offers just service provisioning and gives access to the end user for certain operations i.e. schema/db creation. Keeps it simple.

2) Bind request can take in custom parameters. There could be logic implemented to handle schema/db creation together with credentials. E.g. if the db name passed as a part of custom parameters exists, just create credentials if not also created db.

3) Use [custom actions](https://docs.google.com/document/d/1Dhs4RrvXxyDcmK8LdxbkHcEb_HrpiA4XqVwaIy2sTXg/edit#heading=h.cq2mlq8nfs8p)  for typical service interactions i.e. db creation, backup, restore,etc.

**Comment by MatthiasWinzeler** [comment]
@mcelep We're aware about the catalog constraints. However, these are CF-imposed limitations, and the dynamic catalog will most likely not be used by CF, but by a self-written OSB consumer. The OSBAPI itself does not specify this behavior.

If we disable binding or extend the bind request we lose database/cluster as a service instance entity. I'd like to have these entities as first class resources, we could then nicely model actions, billing etc. on these resources.

We will use your 3.) definitely for actions like backup, restore etc. 
It could be an idea to not 'abuse' service provisioning to create new catalog items, but to have an own custom action for it, i.e. `create cluster` which will then create the catalog items.

Btw you can also follow the discussion in [OSBAPI slack](https://openservicebrokerapi.slack.com/archives/C2S27LBC5/p1516719482000665)

**Comment by mcelep** [comment]
@MatthiasWinzeler i guess even if OSB does not specify such a caching behavior, it would be wise to not rule out/complicate integration with already existing platforms such as CF.

> If we disable binding or extend the bind request we lose database/cluster as a service instance entity. I'd like to have these entities as first class resources, we could then nicely model actions, billing etc. on these resources.

I would keep it simple unless you are 100% sure that these actions on these first class resources you mention are needed.

**Comment by MatthiasWinzeler** [comment]
@mcelep 
I would love to keep it simple. The thing is, we have the following requirements:

- After the cluster is created, there are some extensive operations expected to be offered by the broker (i.e. for creating databases, users and such) which we would like to model as provisioning/bind (for interaction with CF etc.). So each cluster should be a separate catalog item ('service').
- Clusters themselves will be created dynamically. 

As far as I can tell, you cannot solve that without having a dynamic catalog.

**Comment by mcelep** [comment]
@MatthiasWinzeler

> After the cluster is created, there are some extensive operations **expected** to be offered by the broker (i.e. for creating databases, users and such) which we would like to model as provisioning/bind (so that interaction with standard OSB support - CF for example - still works). So each cluster should be a separate catalog item ('service').

Binding support is optional, it definitely might create better user experience if done right. The question is how far should you go for individual service adapters in SB to create that experience? 
Take user creation during binding for example. If you want to do it perfect, even r/w on different database objects will create lots of implementation effort. 

So when you say **expected**, is that as in, you think the users expect it or PMs want it that way?

**Comment by MatthiasWinzeler** [comment]
@mcelep As far as I know, it's the user's expectation. We will have a direct link to them from this week on, so we will question this expectation and make sure it's aligned with what makes sense given OSBAPIs constraints. Probably some of it can be offloaded to them (i.e. just give them a higher-privileged user and they can automate the gory details themselves), while others will have to be part of the 'service'.

**Comment by meip** [comment]
Close in favour for #50
