### ISSUE TITLE
Refactor for Context Object support

### ISSUE THREAD

**Issue by meip** [swisscom/open-service-broker#46]
# Problem
The [context](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#body-4) field was introduced with OSB Spec 2.13. 

## Details
The OSB implementation today covers parts of it already here:
- Provision
https://github.com/swisscom/open-service-broker/blob/853cd090684c6874120900f5acef6a6b55688607/broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/ProvisioningDto.groovy#L11-L12
https://github.com/swisscom/open-service-broker/blob/853cd090684c6874120900f5acef6a6b55688607/broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/ProvisionRequest.groovy#L18-L19

# Proposal
* Implement `context` according to spec
* Backwards must not supported since Cloud Foundry already supports the new `context` field:
https://github.com/cloudfoundry/cloud_controller_ng/blob/0cc31e1333abdc4da16676ced7d57ae0536ae6c3/lib/services/service_brokers/v2/client.rb#L235-L241

# Links
https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/profile.md#context-object

**Comment by ampersand8** [comment]
Implemented with #48
