### ISSUE TITLE
make open-service-broker MariaDB/Galera compatible | every table has a PK

### ISSUE THREAD

**Issue by GETandSELECT** [swisscom/open-service-broker#60]
Hello

A lot of customers wish to run open-service-broker with cf-mysql bosh release from Pivotal.

Quote from [Tips on Converting to Galera](https://mariadb.com/kb/en/library/tips-on-converting-to-galera/)

> Dear Schema Designer:
> - InnoDB only, always have PK.
> (...)

Please make sure every table has a PK, special when there are more than a million rows. For example a DELETE on `service_instance_service_detail` causes the replication to do million x million FULL TABLE scan.

thanks

**Comment by meip** [comment]
We're going to address this in #63.
