### ISSUE TITLE
Add ApplicationUser as Owner to ServiceInstance

### ISSUE THREAD

**Issue by seilc1** [swisscom/open-service-broker#69]
# Problem
There is now way to reference a service instance to a platformGuId. When a maintenance on a platform is planned, it is therefor impossible to inform all the service instances which would be influenced by this maintenance.
This is also true for the binding. If you do not own a service instance put use it (shared service) there should also a way to identifiy you as it's owner.

# Requirements
- [ ] It is possible to find out to which platformGuid a service instance belongs
- [ ] the API has not to change and remain compliant with the OSB API Spec
- [ ] it must not be possible to configure or change the platformGuid via a Request
- [ ] There has to be a platformGuid be retrievable for every service instance
- [ ] it is possible to find out to which platformGuid a service binding belongs

# Proposal
- add a FK to application user to service_instance (owner)
- add a FK to application user to service_binding (owner)
- on provisioning a service_instance the current user should be set as owner
- on binding a service_instnace the current user should be set as owner to the binding
- for already existing service_instances the owner should be set to the first user with the role: `CF_ADMIN`
- for already existing service_bindings the owner should be set to the first user with the role: `CF_ADMIN`

# Links
- [Latest Service Broker API Spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md)

**Comment by ampersand8** [comment]
implemented with #72
