### ISSUE TITLE
MySQL or MariaDB

### ISSUE THREAD

**Issue by Zee-Khan** [swisscom/open-service-broker#9]
As the README says I can use either MySQL or MariaDB, I initially used a MySQL docker (5.7.18) to run the broker, but was running into an error during provisioning of a service.

> provisionRequest.plan.service = null
2017-06-26 14:45:06.629 ERROR 10455 --- [nio-8080-exec-8] c.s.c.s.b.controller.BaseController      : Uncaught error
>java.lang.NullPointerException: Cannot get property 'asyncRequired' on null object

Today I noticed an update to the README.txt showing how to deploy a MariaDB docker (10.1.24-MariaDB-1~jessie) and thought i'd try it out and it works.

> provisionRequest.plan.service = com.swisscom.cloud.sb.broker.model.CFService@6c1141a0

No code changes between the two runs.

Pointing this out for anyone struggling with the same issue.

**Comment by meip** [comment]
I tried to reproduce your issue with the MySQL 5.7.18 Docker Image:
`docker run --name appc-cf-service-broker-mysql -e MYSQL_DATABASE=CFBroker -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3306:3306 -d mysql:5.7.18`

Everything worked as expected. @Zee-Khan Can you provide more details to reproduce the exception?

**Comment by Zee-Khan** [comment]
I was seeing how the provisioning of a service worked so I added a dummy service to the catalog with the asyncRequired flag set to false among other minor changes. Just by doing that, I had the two different outcomes depending on the DB you see in my initial comment. 

Here's my dummy service...

> {
  "guid": "udn9276f-hod4-5432-vw34-6c33d7359c20",
  "name": "service",
  "description": "New Service",
  "bindable": true,
  "asyncRequired": false,
  "internalName": "newService",
  "displayIndex": 1,
  "tags": [],
  "metadata": {
    "version": "1.0",
    "displayName": "Service Enterprise"
  },
  "plans": [
    {
      "guid": "jfkos87r-truz-4567-liop-dfrwscvbnm20",
      "name": "basic",
      "description": "The only service plan",
      "templateId": "service-bosh-template",
      "free": false,
      "displayIndex": 0,
      "containerParams": [
        {
          "template": "",
          "name": "plan",
          "value": "service.basic"
        }
      ],
      "metadata": {
        "concurrency": "100",
        "memory": "512MB",
        "displayName": "Small"
      }
    }
  ]
}

**Comment by meip** [comment]
I successfully added a dummy service successfully with with the service-definition API:
```bash
curl -X PUT \
  http://localhost:8080/custom/admin/service-definition \
  -H 'authorization: Basic Y2ZfZXh0OmNoYW5nZV9tZQ==' \
  -H 'cache-control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{  
  "guid":"udn9276f-hod4-5432-vw34-6c33d7359c20",
  "name":"service",
  "description":"New Service",
  "bindable":true,
  "asyncRequired":false,
  "internalName":"newService",
  "displayIndex":1,
  "tags":[  

  ],
  "metadata":{  
    "version":"1.0",
    "displayName":"Service Enterprise"
  },
  "plans":[  
    {  
      "guid":"jfkos87r-truz-4567-liop-dfrwscvbnm20",
      "name":"basic",
      "description":"The only service plan",
      "templateId":"service-bosh-template",
      "free":false,
      "displayIndex":0,
      "containerParams":[  
        {  
          "template":"",
          "name":"plan",
          "value":"service.basic"
        }
      ],
      "metadata":{  
        "concurrency":"100",
        "memory":"512MB",
        "displayName":"Small"
      }
    }
  ]
}'
```

Afterwards catalog shows the added service:
```bash
curl -X GET \
  http://localhost:8080/v2/catalog \
  -H 'authorization: Basic Y2NfYWRtaW46Y2hhbmdlX21l' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'
```

**Comment by Zee-Khan** [comment]
I'm also able to add the service to the catalog. The error occurs when I attempt to provision the dummy service. I expect the provisioning to fail, obviously, but it failed in two different ways.

Here's the command I used...
```
curl -u 'user:pass' -X PUT \
    -H 'Content-Type: application/json' --data-binary '@provision.json' \
    'http://localhost:8080/v2/service_instances/59ee663f-a964-4a28-8315-47634300ad13'
```

Here's what is in provision.json...
```
{
    "service_id": "udn9276f-hod4-5432-vw34-6c33d7359c20",
    "plan_id": "jfkos87r-truz-4567-liop-dfrwscvbnm20"
}
```

**Comment by meip** [comment]
With d28307099a561e83c98fbccfec0c87bb7822a99c I've added a few Unit tests to cover the ServiceProvisioning behavior.

The problem in your issue is, that you want to create a new service with `"internalName": "newService"` for which the implemented `ServiceProvider` is missing. This implementation is required to do the effective service provisioning as you can image and will be reflected from the loaded beans at runtime: 
https://github.com/swisscom/open-service-broker/blob/develop/broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/common/ServiceProviderLookup.groovy#L35

If you want to test it, simply use a service definition with `"internalName":"dummy"` since a `DummyServiceProvider` is provided here:
https://github.com/swisscom/open-service-broker/blob/develop/broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummyServiceProvider.groovy

We will improve the loading of beans to have a more robust solution for this weakness in future.

**Comment by mcelep** [comment]
@Zee-Khan, do you have any updates/findings?

**Comment by Zee-Khan** [comment]
So I ran into the same bug with MariaDB. I was naive to blame it on MySQL, but that seemed to be the only difference in my setup at the time.

To recreate the bug:
1. POST a service definition
2. DELETE the service definition
3. POST the same service definition
4. Try to provision service.

**Comment by Zee-Khan** [comment]
Service broker is working as expected maintaining unique GUID.
